### ISSUE TITLE
R Markdown

### ISSUE THREAD

**Issue by CasAndreu** [UW-POLS503/pols_503_sp16#1]
#### Some documentation about how to use R Markdown:
- [Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
- Module on [Markdown Basics](http://rmarkdown.rstudio.com/authoring_basics.html): Headers, italics, bold, lists, etc.

**Comment by jrnold** [comment]
We should really lean on http://r4ds.had.co.nz/ (also for practical examples of programming)

**Comment by jrnold** [comment]
A 10 minute basic markdown interactive session: http://commonmark.org/help/tutorial/

**Comment by jrnold** [comment]
And another markdown reference: http://commonmark.org/help/
