### ISSUE TITLE
Add teams

### ISSUE THREAD

**Issue by jrnold** [UW-POLS503/pols_503_sp16#16]
- [x] Add team for all spring 2016 students
- [x] Add team for each student and settings for their private repos. Student + instructors should be able to read/write their repo. All other students will only be able to read.

**Comment by CasAndreu** [comment]
@jrnold I think only organization **owners** can add new members to the organization. Right now I'm just a **member**. Is there a way you can change that?

**Comment by jrnold** [comment]
you're an owner now.

**Comment by CasAndreu** [comment]
Thanks!

**Comment by jrnold** [comment]
Remember to close issues when you've fixed them.
