### ISSUE TITLE
Programming in R (for, if, else, functions)

### ISSUE THREAD

**Issue by CasAndreu** [UW-POLS503/pols_503_sp16#2]
- Prepare 1 module on this
- Look at the code for their projects for examples of when to use: for, if, else, and functions
- Also look at [R for Data Science](http://r4ds.had.co.nz/)

**Comment by CasAndreu** [comment]
Started writing a [module](https://github.com/UW-POLS503/pols_503_sp16/blob/master/lessons/programming_in_R.Rmd) on this

**Comment by jrnold** [comment]
Definitely follow the R for data science. It has practical reasons for how they are used.

**Comment by CasAndreu** [comment]
I just finish a first draft of this [module](https://github.com/UW-POLS503/pols_503_sp16/blob/master/lessons/programming_in_R.Rmd). I have used examples from the students' 501 projects, R for data science, and last years' 503 [lab5](https://github.com/UW-POLS503/pols_503_sp15/blob/master/labs/lab5.Rmd).

**Comment by jrnold** [comment]
Rewrite the learning objectives to use active verbs. See the advice here: http://swcarpentry.github.io/instructor-training/07-design.html

**Comment by jrnold** [comment]
Also, use `##` for the the headings. If these seem too big, you can adjust the CSS. But don't change the semantics of headers to change the look. See the `schedule.Rmd` for example of me adjusting the headers. If you want it for all the lessons, we can add a new css file that all the lessons load.
