### ISSUE TITLE
Get data for Nunn and Wantchekon

### ISSUE THREAD

**Issue by jrnold** [UW-POLS503/pols_503_sp16#22]
Data for Nunn and Wantchekon. 2011. "The Slave Trade and the Origins of Mistrust in Africa." _AER_. We will use this for HW assignments as replication.

**Comment by CasAndreu** [comment]
Found it!

Have it in my dropbox. You should be able to access it [here](https://www.dropbox.com/sh/1gjwgna4dohfkna/AABfzojru39Q5H60gfb8BJV2a?dl=0).
