### ISSUE TITLE
Instructions of submitting assignments and projects

### ISSUE THREAD

**Issue by jrnold** [UW-POLS503/pols_503_sp16#24]
Write instructions for how to submit 
1. assignments (fork repo from `UW-POLS503`, work on in their own repo, pull-request to `UW-POLS503`)
2. project (own repo, work on, submit issue)

Make it as clear and detailed as possible. Include screenshots if need be.

**Comment by CasAndreu** [comment]
I've included a new reference to the website explaining how to submit homework assignments: [Submitting Homework](http://uw-pols503.github.io/pols_503_sp16/submitting-homework)

cc @jrnold

**Comment by CasAndreu** [comment]
I just included another reference to the website about how to submit project assignments:
[Submitting Project Assignments](http://uw-pols503.github.io/pols_503_sp16/submitting-proj-assign)

**Comment by jrnold** [comment]
Put all images in the `img` folder and clean up images in the wrong spot.

**Comment by CasAndreu** [comment]
My bad! I did it locally but never pushed it :) Done!
