### ISSUE TITLE
Lessons on functional form

### ISSUE THREAD

**Issue by jrnold** [UW-POLS503/pols_503_sp16#25]
This should cover
1. Logarithm:
   - review examples. Look at discussion in Wooldridge, Gelman & Hill, Adolph's notes.
   - Need good examples of this. Perhaps Cobb Douglas ? 
2. Squared terms
   - Motivate with examples of U-shaped relationships in theory. E.g. Kuznets curve or environmental Kuznet's curve.
3. General Polynomials
   - Look at Adolph's 503 notes for example. Take fake data. Keep adding polynomial terms until it fits everything.

**Comment by CasAndreu** [comment]
I'll work all day tomorrow on preparing this. Thanks for the notes!

On Wed, Apr 13, 2016 at 10:28 AM, Jeffrey Arnold notifications@github.com
wrote:

> This should cover
> 
>    1.
> 
>    Logarithm:
> - review examples. Look at discussion in Wooldridge, Gelman & Hill,
>     Adolph's notes.
>   - Need good examples of this. Perhaps Cobb Douglas ?
>     2.
>   
>   Squared terms
> - Motivate with examples of U-shaped relationships in theory. E.g.
>     Kuznets curve or environmental Kuznet's curve.
>   3.
>   
>   General Polynomials
> - Look at Adolph's 503 notes for example. Take fake data. Keep adding
>     polynomial terms until it fits everything.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/UW-POLS503/pols_503_sp16/issues/25

## 

Andreu Casas
PhD Student
Department of Political Science
University of Washington
http://andreucasas.com
acasas@uw.edu

**Comment by CasAndreu** [comment]
I just updated the lesson in the [website](http://uw-pols503.github.io/pols_503_sp16/lessons_functional_forms2.html). I'm not covering _General Polynomials_, I don't think I'll have time to address it today. I think it's better to let them think about potential Logarithmic and U-shaped relations in their own project if we have extra time, don't you think?

**Comment by jrnold** [comment]
Sounds good to me. Don't worry about the general polynomials - that can be covered in notes and when discussing bias-variance tradeoff and overfitting.

**Comment by jrnold** [comment]
This isn't building. I'm getting the error message:

```
jrnold@D-69-91-152-20:~/Documents/projects/pols_503_sp16% make
R --slave -e "rmarkdown::render('lessons_functional_forms2.Rmd',encoding='UTF-8')"


processing file: lessons_functional_forms2.Rmd
  |..                                                               |   3%
  ordinary text without R code

  |....                                                             |   5%
label: unnamed-chunk-1 (with options)
List of 1
 $ message: logi FALSE

  |.....                                                            |   8%
  ordinary text without R code

  |.......                                                          |  11%
label: unnamed-chunk-2
Quitting from lines 32-33 (lessons_functional_forms2.Rmd)
Error in file(file, "rt") : cannot open the connection
Calls: <Anonymous> ... withVisible -> eval -> eval -> read.csv -> read.table -> file

Execution halted
make: *** [lessons_functional_forms2.html] Error 1
```

 Also, there are `lessons_functional_forms2.Rmd` and `lessons_functional_forms.Rmd`. Which one is the correct lesson? Delete the other, and add a link on the schedule.

**Comment by CasAndreu** [comment]
Hi Jeff. The right one is `lessons_functional_forms2.Rmd`. I just removed all the files related to `lessons_functional_forms.Rmd` and added a link to the right lesson to the schedule. It's all working for me. Let me know if you still have issues.

**Comment by jrnold** [comment]
Stop working on the weekends! That's an order.
