### ISSUE TITLE
Split programming in R into two lessons

### ISSUE THREAD

**Issue by jrnold** [UW-POLS503/pols_503_sp16#5]
I closed #2 and opened this.

Split programming in R into "writing functions" and "loops and conditionals" modules. Similar to how it is split in R4ds

**Comment by CasAndreu** [comment]
Done! I'll now work on the edits we discussed.

**Comment by jrnold** [comment]
Once you're done close the issue. You can also reference commits relevant to the issue in commit messages, https://help.github.com/articles/autolinked-references-and-urls. You can even close issues by referencing them in commit messages: https://help.github.com/articles/closing-issues-via-commit-messages/
