### ISSUE TITLE
Matrix algebra resources

### ISSUE THREAD

**Issue by jrnold** [UW-POLS503/pols_503_sp16#6]
Add resources for matrix algebra.

@CasAndreu what are the relevant Kahn academy videos that you found?

**Comment by CasAndreu** [comment]
Here is [link](https://www.khanacademy.org/math/precalculus/precalc-matrices) to the Kahn academy lectures, videos, and exercises. They are all very useful and not too long. I would recommend students to skim all the material. Some modules they could skip:
- Elementary matrix row operation
- Row-echelon form and Gaussian elimination
- Practice finding the inverses of 2x2 matrices (the previous videos are already very clear)

**Comment by jrnold** [comment]
Looks okay. I'll check it over. Though I  think we can skip much of the stuff on inverting matrices, and determinants.
